version: '3'

services:
  app:
    build: .
    container_name: aurora
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '8070:8070'
    volumes:
      - ./access_tokens.txt:/access_tokens.txt:ro
      - ./free_tokens.txt:/free_tokens.txt:ro